import type { Component } from 'vue';
import {
  Compass,
  BookOpen,
  Gamepad2,
  UserCheck,
  ShieldCheck,
  User,
  Settings,
  ArrowLeft,
  ArrowRight,
  X,
  Menu,
  ChevronDown,
  ChevronUp,
  ChevronRight,
  ChevronLeft,
  Search,
  Filter,
  RefreshCw,
  Check,
  CheckCircle2,
  AlertTriangle,
  AlertCircle,
  Info,
  HelpCircle,
  Lock,
  Unlock,
  Volume2,
  VolumeX,
  Mic,
  MicOff,
  Download,
  Upload,
  Trash2,
  Edit2,
  Plus,
  Minus,
  ExternalLink,
  Play,
  PlayCircle,
  Star,
  Coins,
  Trophy,
  Medal,
  Flame,
  Sparkles,
  Lightbulb,
  BookMarked,
  Bot,
  Target,
  Clock,
  LayoutGrid,
  ClipboardList,
  Calendar,
  Award,
  Shield,
  Share2,
  Eye,
  EyeOff,
  Printer,
  Swords,
  History,
  RotateCcw,
  LogIn,
  LogOut,
  GraduationCap,
  Sparkle
} from 'lucide-vue-next';

export const ICON_MAP: Record<string, Component> = {
  // 🧭 Navigation & Core Tabs
  home: Compass,
  compass: Compass,
  learn: BookOpen,
  'book-open': BookOpen,
  play: Gamepad2,
  gamepad: Gamepad2,
  growth: UserCheck,
  'user-check': UserCheck,
  parent: ShieldCheck,
  'shield-check': ShieldCheck,
  user: User,
  settings: Settings,
  'graduation-cap': GraduationCap,

  // ⬅️ Directions & Actions
  back: ArrowLeft,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  close: X,
  x: X,
  menu: Menu,
  'chevron-down': ChevronDown,
  'chevron-up': ChevronUp,
  'chevron-right': ChevronRight,
  'chevron-left': ChevronLeft,
  'rotate-ccw': RotateCcw,
  refresh: RefreshCw,
  'refresh-cw': RefreshCw,
  login: LogIn,
  logout: LogOut,

  // 🔍 Utility & Operations
  search: Search,
  filter: Filter,
  check: Check,
  'check-circle': CheckCircle2,
  alert: AlertTriangle,
  'alert-triangle': AlertTriangle,
  'alert-circle': AlertCircle,
  info: Info,
  help: HelpCircle,
  lock: Lock,
  unlock: Unlock,
  volume: Volume2,
  'volume-x': VolumeX,
  mic: Mic,
  'mic-off': MicOff,
  download: Download,
  upload: Upload,
  trash: Trash2,
  edit: Edit2,
  plus: Plus,
  minus: Minus,
  'external-link': ExternalLink,
  share: Share2,
  eye: Eye,
  'eye-off': EyeOff,
  printer: Printer,

  // 🌟 Domain / Gamification / Learning
  'play-circle': PlayCircle,
  'play-action': Play,
  star: Star,
  coin: Coins,
  coins: Coins,
  trophy: Trophy,
  medal: Medal,
  flame: Flame,
  sparkles: Sparkles,
  sparkle: Sparkle,
  lightbulb: Lightbulb,
  book: BookMarked,
  'book-marked': BookMarked,
  bot: Bot,
  target: Target,
  clock: Clock,
  grid: LayoutGrid,
  'layout-grid': LayoutGrid,
  'clipboard-list': ClipboardList,
  calendar: Calendar,
  award: Award,
  shield: Shield,
  swords: Swords,
  history: History
};

export type IconName = keyof typeof ICON_MAP;

export type IconTone =
  | 'inherit'
  | 'brand'
  | 'muted'
  | 'success'
  | 'warning'
  | 'danger'
  | 'info'
  | 'learning'
  | 'growth'
  | 'challenge';

export const ICON_TONE_CLASS_MAP: Record<IconTone, string> = {
  inherit: 'text-current',
  brand: 'text-brand-strong',
  muted: 'text-text-muted',
  success: 'text-success',
  warning: 'text-warning',
  danger: 'text-danger',
  info: 'text-info',
  learning: 'text-learning',
  growth: 'text-growth',
  challenge: 'text-challenge'
};

